// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using academystudentsbackend.Models;

#nullable disable

namespace academystudentsbackend.Migrations
{
    [DbContext(typeof(CourseContext))]
    [Migration("20231207111018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("academystudentsbackend.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("academystudentsbackend.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("academystudentsbackend.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Category = "design",
                            Description = "Qrafik dizayn dərslərini təqdim edirik.Dərslər həftə ərzində 3dəfə 60dəq və ya 2dəfə 90dəq həcmində təşkil olunur Məşğələlər fərdi şəkildə təşkil olunur.Bu proqram çərçivəsində siz photoshopla köhnə şəkillərin bərpasını,ağ-qara şəkillərin rənglənmasini,üz montajını,kollaj və panarama şəkillərin yiğılmasını,buklet, flayer, banner, vizitka,poster,retuş,animasiyaların yığılmasını və bir çox yeni praktiki biliklər əldə edəcəksiniz.",
                            Image = "photoshop.png",
                            Name = "Adobe Photoshop",
                            Price = 90m
                        },
                        new
                        {
                            CourseId = 2,
                            Category = "design",
                            Description = "Qrafik dizayn dərslərini təqdim edirik.Dərslər həftə ərzində 3dəfə 60dəq və ya 2dəfə 90dəq həcmində təşkil olunur Məşğələlər fərdi şəkildə təşkil olunur.Bu proqram çərçivəsində siz illustratorla flat logo,effektlər,posterlər,vizika,flayer,bukletlər yığılması,vektorların,cədvəllərin,diaqramların çəkilməsini öyrənəcəksiniz.",
                            Image = "illustrator.png",
                            Name = "Adobe Illustrator",
                            Price = 90m
                        },
                        new
                        {
                            CourseId = 3,
                            Category = "design",
                            Description = "Qrafik dizayn dərslərini təqdim edirik.Dərslər həftə ərzində 3dəfə 60dəq və ya 2dəfə 90dəq həcmində təşkil olunur Məşğələlər fərdi şəkildə təşkil olunur.Bu proqram çərçivəsində siz corel draw-la logo,buklet,vizitka,poster,plokat yığılmasını,CMYK rəng ayırımı və effektlər barədə praktiki biliklərə yiyələnəcəksiniz.",
                            Image = "coreldraw.png",
                            Name = "Corel Draw",
                            Price = 90m
                        },
                        new
                        {
                            CourseId = 4,
                            Category = "design",
                            Description = "Qrafik dizayn dərslərini təqdim edirik.Dərslər həftə ərzində 3dəfə 60dəq və ya 2dəfə 90dəq həcmində təşkil olunur Məşğələlər fərdi şəkildə təşkil olunur.Bu proqram çərçivəsində siz indesign-la flat logo,effektlər,posterlər,vizika,flayer,bukletlər yığılması,vektorların,cədvəllərin,diaqramların çəkilməsini öyrənəcəksiniz.",
                            Image = "indesign.png",
                            Name = "Adobe InDesign",
                            Price = 120m
                        },
                        new
                        {
                            CourseId = 5,
                            Category = "office",
                            Description = "Dərslər həftədə 3 dəfə 1 saat və ya 2dəfə 90 dəqiqə ərzində tədris olunur.Bu proqram çərçivəsində siz word proqramında mətnlərin tərtibini,cədvəlləri,fayllara şifrə qoymağı,sənədlərin çapını,səhifə başlığı və sonu anlayışlarını dərindən öyrənib,praktiki biliklər əldə edəcəksiniz.",
                            Image = "word.png",
                            Name = "Microsoft Word",
                            Price = 90m
                        },
                        new
                        {
                            CourseId = 6,
                            Category = "office",
                            Description = "Dərslər həftədə 3 dəfə 1 saat və ya 2dəfə 90 dəqiqə ərzində tədris olunur.Bu proqram çərçivəsində siz powerpoint proqramında təqdimat,slide show,naviqator,intro,poster,kiçik həcmdə video montaj,cədvəl,diaqram yığmaqı öyrənəcək,praktiki biliklər əldə edəcəksiniz.",
                            Image = "powerpoint.png",
                            Name = "Microsoft Powerpoint",
                            Price = 90m
                        },
                        new
                        {
                            CourseId = 7,
                            Category = "office",
                            Description = "Dərslər həftədə 3 dəfə 1 saat və ya 2dəfə 90 dəqiqə ərzində tədris olunur.Bu proqram çərçivəsində siz exceldə ticarət anlayışlarını,endirim,əmək haqqının hesablanması,kredit,ümumi cəm,konselidasiya,məlumatların yoxlanması,diaqram,valyuta dəyişimi və s əməliiyatları yerinə yetirməyi,bununla yanaşı ДВССЛ,ВПР,ЕСЛИ,ПОИСКПОЗ,ИНДЕКС kimi funksiyalarla çalışmağı öyrənəcək,praktiki biliklər qazanacaqsınız.",
                            Image = "excel.png",
                            Name = "Microsoft Excel",
                            Price = 90m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("academystudentsbackend.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("academystudentsbackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("academystudentsbackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("academystudentsbackend.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("academystudentsbackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("academystudentsbackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
